name: 'Manifest updater'
description: 'Update the manifest that is used to identify packs'
inputs:
  ACCESS_TOKEN:
    description: 'A secret token that is used to access the github API'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
